package deletedflag

import (
	"log/slog"
	"net/http"

	"github.com/go-chi/render"

	"github.com/FischukSergey/urlshortener.git/config"
	"github.com/FischukSergey/urlshortener.git/internal/app/middleware/auth"
)

// AutoGenerated структура для удаления url
type AutoGenerated []string

// DeleteShortURL - функция для удаления коротких URL по идентификатору пользователя.
func DeleteShortURL(log *slog.Logger, delChan chan config.DeletedRequest) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {

		w.Header().Set("Content-Type", "application/json")

		userID := r.Context().Value(auth.CtxKeyUser).(int)

		var req AutoGenerated

		err := render.DecodeJSON(r.Body, &req)
		if err != nil {
			w.WriteHeader(http.StatusBadRequest)
			log.Error("not read body request")
			return
		}

		//пишем в буферизированный канал данные запроса
		for _, val := range req {
			delChan <- config.DeletedRequest{
				ShortURL: val,
				UserID:   userID,
			}
		}

		w.WriteHeader(http.StatusAccepted)

	}
}
